spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/film_management
    username: postgres
    password: B855sh48
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect